sudo: false
language: node_js
node_js:
  - '6'
  - '5'
  - '4'

cache:
  directories:
    - node_modules
before_install: npm install -g npm@latest
before_script:
  - npm run lint
  # - npm run build # will need this when we do sauce testing of compiled files
script:
  - npm run test-coverage
  # - npm run test-dist # test the compiled files
after_success:
  - npm run codecov
before_deploy:
    - npm run build
deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
  email: clayreimann@gmail.com
  api_key:
    secure: TZHqJ9Kh2Qf0GAVDjEOQ01Ez6rGMYHKwVLOKTbnb7nSzF7iiGNT4UwzvYawm0T9p1k7X1WOqW3l7OEbIwoKl7/9azT4BBJm7qUMRfB9Zio5cL3rKubJVz7+LEEIW4iBeDWLanhUDgy9BO2JKCt8bfp/U2tltgXtu9Fm/UFPALI8=
