# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GitHub.js
description: > # Github.js is a library that allows easy access to GitHub's REST API.
url: https://michael.github.io
baseurl: /github
git_repo: https://github.com/michael/github
